### ISSUE TITLE
rename into make

### ISSUE THREAD

**Issue by mklabs** [mklabs/make#5]
https://www.npmjs.com/package/make

@danielchatfield Daniel, do you think we could init the transfer thing sometime soon ? How's your exams going btw ?

**Comment by danielchatfield** [comment]
@mklabs I've added you as a collaborator :)

Exams all over now.

**Comment by mklabs** [comment]
Adding you as well :)

**Comment by mklabs** [comment]
@danielchatfield Hi, I hope you're doing ok. I'm currently in the process of renaming the package and pushing it to the registry.
